server:
    port: 10050
    context-path: /ferlenco
    
logging:
  config: ./config/log4j.xml

spring:
  data:
    mongodb:
      database: furlenco
      host: localhost
      port: 27017
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/mydemo?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: abc123
    test-on-borrow: true
    validation-query: SELECT 1